### ISSUE TITLE
[Request] Save proxy based on proxy information (Location, Country, Anonimity etc)

### ISSUE THREAD

**Issue by Nexuzzzz** [yunginnanet/pxndscvm#3]
You could add a option to save proxies based on location, country or anonimity (by using 3rd party API's)
The reason why this shouldn't be done WHILE filtering is because it would slow the process down a lot.

Just a small request, feel free to ignore this lol

**Comment by yunginnanet** [comment]
(this will likely be a part of a sister package that interfaces with this one)

**Comment by Nexuzzzz** [comment]
> (this will likely be a part of a sister package that interfaces with this one)

ight
